[package]
name = "xindex-signer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
xindex-shared.workspace = true
xindex-chain-thor.workspace = true
xindex-chain-btc.workspace = true
alloy = { workspace = true }
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
async-trait = "0.1"
bitcoin.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true }
wiremock.workspace = true
serde_json.workspace = true
