[package]
name = "xindex-vultisig-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
xindex-custody-core.workspace = true
xindex-custody-node.workspace = true
xindex-shared.workspace = true
bitcoin.workspace = true

[dev-dependencies]
alloy-primitives.workspace = true
tokio.workspace = true
