[package]
name = "xindex-xrp-tx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
k256 = { version = "0.13", default-features = false, features = ["ecdsa", "arithmetic"] }
sha2.workspace = true
ripemd.workspace = true
thiserror.workspace = true
