[package]
name = "xindex-chain-btc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
bdk_esplora.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
